### ISSUE TITLE
`TypeError: Cannot read property 'split' of undefined` when 'from' address is blank

### ISSUE THREAD

**Issue by shaneboulden** [T0MASD/ukko#4]
I've received several emails with a blank `from` address, which seems to be causing this issue:

```
8:07:22 AM	Error	TypeError: Cannot read property 'split' of undefined
                                        getLabels	@ Code.gs:69
                                        assignLabels	@ Code.gs:42
                                        runUkko	@ Code.gs:18
```

**Comment by T0MASD** [comment]
Thanks for logging the issue, I have created the MR linked above, I'd appreciate if you please review it please and confirm this fixes your issue.

**Comment by shaneboulden** [comment]
The fix works great, thanks @T0MASD!
