### ISSUE TITLE
Wondering why we have a sub label....

### ISSUE THREAD

**Issue by boxallw** [T0MASD/ukko#7]
Most labels have a "redhat" sub label under lists. Any ideas why?

**Comment by T0MASD** [comment]
@boxallw the way sample script is setup for mailing lists when email is received from external domain, a sublabel is created: 
https://github.com/T0MASD/ukko/blob/main/modules/ukko.js#L150

you may replace mydomain with redhat or remove that logic altogether. Please let me know how it goes.

**Comment by boxallw** [comment]
Hi Tomas

This is how it looks for me:

[image: image.png]

Why are there sublabels of redhat under many?

Cheers


*Wayne Boxall*
Account Technology Strategist – Automation, Containers and Cloud
*Mobile*: 0412 816 992
*Email*: ***@***.***

**Comment by T0MASD** [comment]
when an email is received via a mailing list from a domain that isn't matching  'mydomain' a sublabel is created https://github.com/T0MASD/ukko/blob/main/modules/ukko.js#L150
